# 제로베이스 데이터 사이언스 스쿨 3기 SQL 과제 2
- 유가 데이터 분석

### 8문제 총 100점

- 1번 5점
- 2번 5점
- 3번 10점
- 4번 30점
- 5번 10점
- 6번 10점
- 7번 15점
- 8번 15점

### 1 ~ 8번 모두 본 노트북 파일에 답안 작성해서 제출해주세요 :)

---

In [9]:
import mysql.connector
import pandas as pd
import numpy as np
import googlemaps
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from bs4 import BeautifulSoup

In [3]:
conn = mysql.connector.connect(
    user = 'root',
    password = 'password',
    database = 'oneday'
)

In [4]:
cursor = conn.cursor()

문제 1.

주유소 데이터를 저장할 테이블을 다음의 구조로 생성하세요. (PDF 파일 참고)

In [4]:
# GAS_BRAND 테이블 생성
cursor.execute('create table GAS_BRAND(id int primary key auto_increment, name varchar(16))')

In [4]:
#Gas_STATION 테이블 생성
cursor.execute('create table GAS_STATION(id int primary key auto_increment, brand int, name varchar(64), city varchar(2), gu varchar(16), address varchar(128), gasoline int, diesel int, self boolean, car_wash boolean, charging_station boolean, car_maintenance boolean, convenience_store boolean, 24_hours boolean, lat decimal(16, 14), lng decimal(17, 14), foreign key(brand) references gas_brand(id))')

문제 2.

Python 코드로 GAS_BRAND 데이터를 다음과 같이 입력하고 확인하세요. (PDF 파일 참고)

In [7]:
gas_brand_info = [(1, 'SK에너지'), (2, '현대오일뱅크'), (3, 'GS칼텍스'), (4, 'S-OIL'),(5, '알뜰주유소'), (6, '자가상표')]
sql = 'insert into gas_brand values (%s, %s)'
for i in gas_brand_info:
    cursor.execute(sql, i)
    print(i)
    conn.commit()

(1, 'SK에너지')
(2, '현대오일뱅크')
(3, 'GS칼텍스')
(4, 'S-OIL')
(5, '알뜰주유소')
(6, '자가상표')

제출 1.
- Table 생성 결과 : Desc GAS_BRAND; Desc GAS_STATION;

In [4]:
cursor.execute('desc gas_brand')
result = cursor.fetchall()
result

[('id', 'int', 'NO', 'PRI', None, 'auto_increment'),
 ('name', 'varchar(16)', 'YES', '', None, '')]

In [5]:
cursor.execute('desc gas_station')
result = cursor.fetchall()
result

[('id', 'int', 'NO', 'PRI', None, 'auto_increment'),
 ('brand', 'int', 'YES', 'MUL', None, ''),
 ('name', 'varchar(64)', 'YES', '', None, ''),
 ('city', 'varchar(2)', 'YES', '', None, ''),
 ('gu', 'varchar(16)', 'YES', '', None, ''),
 ('address', 'varchar(128)', 'YES', '', None, ''),
 ('gasoline', 'int', 'YES', '', None, ''),
 ('diesel', 'int', 'YES', '', None, ''),
 ('self', 'tinyint(1)', 'YES', '', None, ''),
 ('car_wash', 'tinyint(1)', 'YES', '', None, ''),
 ('charging_station', 'tinyint(1)', 'YES', '', None, ''),
 ('car_maintenance', 'tinyint(1)', 'YES', '', None, ''),
 ('convenience_store', 'tinyint(1)', 'YES', '', None, ''),
 ('24_hours', 'tinyint(1)', 'YES', '', None, ''),
 ('lat', 'decimal(16,14)', 'YES', '', None, ''),
 ('lng', 'decimal(17,14)', 'YES', '', None, '')]

제출 2.
- GAS_BRAND 조회 결과 : SELECT * FROM GAS_BRAND;

In [32]:
cursor.execute('select * from gas_brand')
result = cursor.fetchall()
result

[(1, 'SK에너지'),
 (2, '현대오일뱅크'),
 (3, 'GS칼텍스'),
 (4, 'S-OIL'),
 (5, '알뜰주유소'),
 (6, '자가상표')]

문제 3.

다음의 함수와 그 함수를 테스트하는 코드를 작성하세요. (PDF 파일 참고)

- 화폐단위 문자형을 입력받아 숫자형으로 반환하는 함수 (테스트 입력 : ‘1,000’)
- 주유소 브랜드를 입력하면 GAS_BRAND 데이터를 참고하여 ID 를 반환하는 함수 (테스트 입력 : ‘SK에너지’) - 주소를 입력받아 구 이름을 반환하는 함수 (테스트 입력 : ‘서울시 강남구 헌릉로 730’)
- 주소를 입력받아 위도, 경도를 반환하는 함수 (테스트 입력 : ‘서울시 강남구 헌릉로 730’)

제출 3.
- 각 함수 및 테스트 코드와 실행결과

In [10]:
# 화폐단위 변환 함수
def won(money):
    return int(money.replace(',',''))

# Barnd-ID 반환 함수
def brand_id(brand):
    if brand == 'HD현대오일뱅크':
        brand = '현대오일뱅크'
        
    try:
        cursor.execute('select id from gas_brand where name = %s', (brand,))
        result = cursor.fetchall()

        return result[0][0]
    
    except:
        return 6

# 구 이름 반환 함수
def gu_name(address):
    gu_name = address.split(' ')[1]
    return gu_name

# 위도, 경도 반환 함수

def latlng(address):
    gmaps_key = 'gmaps_key'
    gmaps = googlemaps.Client(key=gmaps_key)
    tmp = gmaps.geocode(address, language = 'ko')
    if len(tmp) > 0:
        lat, lng = tmp[0]['geometry']['location']['lat'], tmp[0]['geometry']['location']['lng']
        return lat, lng
    return ''

In [6]:
 # test won
result = won('1,000')
print(result, type(result))

# test id
result = brand_id('HD현대오일뱅크')
print(result)

# test gu_name
result = gu_name('서울시 강남구 헌릉로 730')
print(result)

# test latlng
result = latlng('서울시 강남구 헌릉로 730')
print(result)

1000 <class 'int'>
2
강남구
(37.4665675, 127.1190803)

문제 4.

Python 코드에서 주유소 페이지에서 데이터를 가져올때, GAS_STATION 테이블에 바로 입력하도록 수정하세요. (앞서 생 성한 함수활용)
- 주의. city 는 ‘서울’ 로 고정, 부가정보 데이터 타입
- 입력된 데이터의 총 갯수를 쿼리하여 결과를 확인합니다. - 입력된 데이터 상위 10개를 쿼리하여 결과를 확인합니다.


제출 4.
- 주유소 데이터 관련 코드 (ipynb)

In [7]:
url = 'https://www.opinet.co.kr/searRgSelect.do'
driver = webdriver.Chrome()
driver.get(url)

In [8]:
req = driver.page_source
soup = BeautifulSoup(req, 'html.parser')

- 순서 정리 
1. 구 입력
2. 조회
3. 주유소별 정보 조회(클릭)
4. BeautifulSoup으로 페이지 정보 가져오기(브랜드, 매장이름, 구, 전체 주소, 휘발유, 경유 가격, 셀프 주유, 세차, 충전, 경정비, 편의점, 24시간 영업 여부, 위도, 경도 정보)
5. sql 데이터 테이블 정보 입력

In [9]:
# gu_list 생성
gu_list = []
for i in range (2, 27):
    gu_names = soup.select('#SIGUNGU_NM0 > option:nth-child({})'.format(i))
    gu_list.append(gu_names[0].text)

In [10]:
# details click()
# 세차장
cwsh = driver.find_element(By.CSS_SELECTOR, '#CWSH_YN')
cwsh.click()

# 경정비
maint = driver.find_element(By.CSS_SELECTOR, '#MAINT_YN')
maint.click()

# 편의점
cvs = driver.find_element(By.CSS_SELECTOR, '#CVS_YN')
cvs.click()

# 경정비
sel24 = driver.find_element(By.CSS_SELECTOR, '#SEL24_YN')
sel24.click()

In [11]:
# 주유소 목록 클릭
oil_station = driver.find_element(By.CSS_SELECTOR, '#body1 > tr:nth-child(1) > td.rlist > a')
oil_station.click()

In [12]:
# 주유소 정보 페이지
req = driver.page_source
soup = BeautifulSoup(req, 'html.parser')

In [13]:
# 브랜드, 매장이름, 구, 전체 주소, 휘발유, 경유 가격, 셀프 주유, 세차, 충전, 경정비, 편의점, 24시간 영업 여부, 위도, 경도 정보

def insert_info():
    req = driver.page_source #주유소 정보 페이지를 BeatifulSoup으로 처리
    soup = BeautifulSoup(req, 'html.parser')

    #브랜드 이름
    brand_info = soup.select('#poll_div_nm')
    brand = brand_info[0].text
    brand

    #brand
    id_info = brand_id(brand)
    id_info

    #매장 이름
    name_info = soup.select('#os_nm')
    name = name_info[0].text

    #주소
    address_info = soup.select('#rd_addr')
    address = address_info[0].text
    address

    #구
    gu = gu_name(address)
    gu

    #휘발유 가격
    gas_info = soup.select('#b027_p')
    gas_price = won(gas_info[0].text)
    gas_price

    #경유 가격
    diesel_info = soup.select('#d047_p')
    diesel_price = won(diesel_info[0].text)
    diesel_price

    # 셀프 주유
    self_yn = soup.select('#self_icon')
    if len(self_yn) > 0:
        self_yn = 1
    else:
        self_yn = 0
    self_yn

    #세차장
    wash_yn = soup.select('#cwsh_yn')
    if wash_yn[0].get('src') == '/images/user/gis/oil_station_service1_01.gif':
        wash_yn = 1
    else:
        wash_yn = 0

    #충전소
    lpg_yn = soup.select('#lpg_yn')
    if lpg_yn[0].get('src') == '/images/user/gis/oil_station_service1_02_01.gif':
        lpg_yn = 1
    else:
        lpg_yn = 0

    #경정비
    maint_yn = soup.select('#maint_yn')
    if maint_yn[0].get('src') == '/images/user/gis/oil_station_service1_03.gif':
        maint_yn = 1
    else:
        maint_yn = 0

    #편의점
    cvs_yn = soup.select('#cvs_yn')
    if cvs_yn[0].get('src') == '/images/user/gis/oil_station_service1_04.gif':
        cvs_yn = 1
    else:
        cvs_yn = 0

    #편의점
    sel24_yn = soup.select('#sel24_yn')
    if sel24_yn[0].get('src') == '/images/user/gis/oil_station_service1_05.gif':
        sel24_yn = 1
    else:
        sel24_yn = 0

    #위도, 경보
    lat = latlng(address)[0]
    lng = latlng(address)[1]
    
    #sql insert 쿼리문
    data_list = (id_info, name, gu, address, gas_price, diesel_price, wash_yn, self_yn, lpg_yn, maint_yn, cvs_yn, sel24_yn, lat, lng )
    sql = 'insert into gas_station values(NULL, %s, %s, "서울", %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)' 
    cursor.execute(sql, data_list)
    result = cursor.fetchall()
    print('OK')
    conn.commit()

In [ ]:
for i in gu_list:
    gu_search = driver.find_element(By.CSS_SELECTOR, '#SIGUNGU_NM0')
    gu_search.send_keys(i)

    search_btn = driver.find_element(By.CSS_SELECTOR, '#searRgSelect') #조회
    search_btn.click()

    print(i)
    time.sleep(5)

    station_len = int(driver.find_element(By.CSS_SELECTOR, '#totCnt').text) #주유소 목록 갯수

    for j in range(1, station_len+1):
        oil_station = driver.find_element(By.CSS_SELECTOR, '#body1 > tr:nth-child({}) > td.rlist > a'.format(j))
        oil_station.click()

        print(j)

        insert_info()

In [15]:
cursor.execute('select count(*) from gas_station limit 2')
result = cursor.fetchall()
result

[(363,)]

In [16]:
driver.close()

문제 5.

시각화 프로젝트를 위하여 다음의 규칙으로 쿼리하여 CSV 파일로 저장합니다. (Python 코드로 작성)
- 전체 데이터를 가져오는데, 주유소 브랜드 아이디 대신 브랜드명이 표시되어야 합니다. (정렬 : 주유소 매장 아이디 순)
- 다음의 형식으로 저장되어야 함 (브랜드 이름, 칼럼 명 주의, id : GAS_STORE.id)

제출 5.
- 시각화 프로젝트 관련 코드 (ipynb), 결과 파일 (csv)

In [ ]:
sql = 'select s.id, b.name, s.name, city, gu, address, gasoline, diesel, self, car_wash, charging_station, car_maintenance, convenience_store, 24_hours, lat, lng from gas_station s, gas_brand b where b.id = s.brand order by s.id'
cursor.execute(sql)
result = cursor.fetchall()
result

In [36]:
df = pd.DataFrame(result)
df.columns = ['id','brand','name', 'city', 'gu', 'address', 'gasoline', 'diesel', 'self', 'car_wash', 'charging_station', 'car_maintenance', 'convenience_store', '24_hours', 'lat', 'lng']
df.to_csv('./seoul_oil_station.csv', index=False, encoding='euc-kr')

문제 6.

위도, 경도 정보를 이용하여 미왕빌딩에서 1킬로 이내에 위치한 주유소 정보를 검색하세요.

- 주유소 아이디, 주유소 브랜드명, 주유소 매장명, 주소, 미왕빌딩으로 부터의 거리 (km)

제출 6.
- 쿼리, 결과

In [37]:
#미왕빌딩 위도, 경도 : 37.49570, 127.0294
sql = "select s.id, b.name as brand, s.name, s.address, (6371*acos(cos(radians(37.49570))*cos(radians(s.lat))*cos(radians(s.lng)-radians(127.0294))+sin(radians(37.49570))*sin(radians(s.lat)))) as distance " + \
       "from GAS_BRAND as b, GAS_STATION as s " + \
       "where s.brand = b.id " + \
       "having distance <= 1 " + \
       "order by distance"

cursor.execute(sql)
result = cursor.fetchall()

for i in result:
    print(i)

(11, 'SK에너지', 'SK서광주유소', '서울 강남구 역삼로 142', 0.5243211275171381)
(212, '현대오일뱅크', 'HD현대오일뱅크㈜직영 서초제일주유소', '서울 서초구 사임당로 116 (서초동)', 0.8284739328955923)
(8, 'S-OIL', '극동유화㈜ 개나리주유소', '서울 강남구 언주로 423 (역삼동)', 0.9420044011971338)
(15, 'GS칼텍스', '지에스칼텍스㈜에너지플러스허브GS타워', '서울 강남구 논현로 516 (역삼동)', 0.9940554792283361)

문제 7.

위도, 경도 정보를 이용하여 미왕빌딩에서 셀프주유가 가능하고 24시간이면서 편의점이 있는 가장 가까운 주유소 10개를 휘 발유 가격이 가장 저렴한 순으로 정렬하여 조회하세요.

- 주유소 아이디, 주유소 브랜드명, 주유소 매장명, 주소, 휘발유 가격, 부가정보 (셀프, 24시간, 편의점 여부), 미왕빌딩으로 부터의 거리 (km)


제출 7.
- 쿼리, 결과

In [38]:
sql = "select * from (select s.id, b.name as brand, s.name, s.address, gasoline, self, 24_hours, convenience_store, (6371*acos(cos(radians(37.49570))*cos(radians(s.lat))*cos(radians(s.lng)-radians(127.0294))+sin(radians(37.49570))*sin(radians(s.lat)))) as distance " + \
       "from GAS_BRAND as b, GAS_STATION as s " + \
       "where s.brand = b.id " + \
       "and self = 1 and 24_hours = 1 and convenience_store = 1 " + \
       "order by distance limit 10) as tmp " + \
       "order by tmp.gasoline"

cursor.execute(sql)
result = cursor.fetchall()
for i in result:
    print(i)

(305, 'SK에너지', '행촌주유소', '서울 영등포구 도신로 130 (신길동)', 1615, 1, 1, 1, 10.959297310776256)
(255, 'GS칼텍스', '지에스칼텍스(주)가든파이브주유소', '서울 송파구 탄천동로 740', 1653, 1, 1, 1, 5.2827712432887886)
(188, 'SK에너지', '행촌제2주유소', '서울 서대문구 성산로 490 (대신동)', 1659, 1, 1, 1, 10.693506364333043)
(119, 'GS칼텍스', '대득에너지(금천셀프주유소)', '서울 금천구  시흥대로 81 (시흥동)', 1665, 1, 1, 1, 12.696701031304674)
(289, '현대오일뱅크', '현대오일뱅크(주)직영 양천현대셀프주유소', '서울 양천구 안양천로 1179 (목동)', 1669, 1, 1, 1, 14.20307474522575)
(313, 'SK에너지', 'SK에너지(주) 기린주유소', '서울 영등포구 선유로 270', 1674, 1, 1, 1, 12.322943085058792)
(264, 'SK에너지', '백제고분로주유소', '서울 송파구 오금로 143 (방이동)', 1683, 1, 1, 1, 7.932458022563731)
(214, 'SK에너지', '대신석유(주)대우주유소', '서울 서초구 양재대로 173 (양재동)', 1699, 1, 1, 1, 3.725089708574418)
(216, 'GS칼텍스', '지에스칼텍스(주)남서울주유소', '서울 서초구 나루터로 83 (잠원동)', 1769, 1, 1, 1, 2.455536628220638)
(317, 'GS칼텍스', 'SJ오일(주) 여의도주유소', '서울 영등포구 은행로 64', 2295, 1, 1, 1, 9.936066808539833)

문제 8.

구별로 주유소 브랜드 별 휘발유 평균가격을 조회하여 저렴한 순으로 출력하세요.

- 구 이름, 주유소 브랜드 이름, 휘발유 평균 가격

제출 8.
- 쿼리, 결과

In [43]:
sql = 'select s.gu, b.name, avg(s.gasoline) as avg_gasoline from gas_station s, gas_brand b where b.id = s.brand group by gu, b.name order by avg(gasoline)'
cursor.execute(sql)
result = cursor.fetchall()
for i in result:
    print(i)

('서초구', '자가상표', Decimal('1569.0000'))
('양천구', 'S-OIL', Decimal('1582.0000'))
('은평구', '현대오일뱅크', Decimal('1600.6667'))
('강서구', '알뜰주유소', Decimal('1606.6667'))
('중랑구', 'GS칼텍스', Decimal('1607.0000'))
('서대문구', 'GS칼텍스', Decimal('1609.0000'))
('성동구', 'S-OIL', Decimal('1610.5000'))
('성북구', 'GS칼텍스', Decimal('1611.0000'))
('관악구', '알뜰주유소', Decimal('1612.0000'))
('관악구', '현대오일뱅크', Decimal('1612.0000'))
('도봉구', 'GS칼텍스', Decimal('1614.3333'))
('성동구', 'GS칼텍스', Decimal('1615.0000'))
('강북구', 'GS칼텍스', Decimal('1617.6667'))
('은평구', 'GS칼텍스', Decimal('1618.8000'))
('양천구', '알뜰주유소', Decimal('1619.0000'))
('강북구', 'SK에너지', Decimal('1622.7500'))
('영등포구', 'S-OIL', Decimal('1624.3333'))
('광진구', '현대오일뱅크', Decimal('1624.4000'))
('성북구', 'SK에너지', Decimal('1624.5000'))
('도봉구', 'S-OIL', Decimal('1624.7500'))
('강북구', 'S-OIL', Decimal('1625.0000'))
('마포구', '현대오일뱅크', Decimal('1625.6667'))
('영등포구', '현대오일뱅크', Decimal('1625.8333'))
('강북구', '현대오일뱅크', Decimal('1627.0000'))
('은평구', 'SK에너지', Decimal('1629.3333'))
('구로구', 'GS칼텍스', Decimal('1629.5000'))
('구로구', '현대오일뱅크', Decimal('1632.0000'))
('도봉구', 'SK에너지', Decimal('1633.0000'))
('성북구', '현대오일뱅크', Decimal('1635.1667'))
('도봉구', '현대오일뱅크', Decimal('1635.2000'))
('서대문구', '현대오일뱅크', Decimal('1635.3333'))
('동대문구', 'GS칼텍스', Decimal('1638.3333'))
('중랑구', 'S-OIL', Decimal('1639.2500'))
('구로구', 'SK에너지', Decimal('1639.7500'))
('노원구', '현대오일뱅크', Decimal('1640.0000'))
('금천구', 'SK에너지', Decimal('1641.0000'))
('양천구', 'GS칼텍스', Decimal('1643.7500'))
('강서구', '현대오일뱅크', Decimal('1644.2000'))
('서대문구', 'S-OIL', Decimal('1645.0000'))
('중랑구', 'SK에너지', Decimal('1649.0000'))
('동대문구', '현대오일뱅크', Decimal('1649.5000'))
('동대문구', 'S-OIL', Decimal('1651.0000'))
('동대문구', 'SK에너지', Decimal('1652.2000'))
('송파구', 'S-OIL', Decimal('1653.0000'))
('금천구', 'S-OIL', Decimal('1655.0000'))
('노원구', 'S-OIL', Decimal('1655.2500'))
('마포구', 'S-OIL', Decimal('1657.0000'))
('양천구', 'SK에너지', Decimal('1658.0000'))
('양천구', '현대오일뱅크', Decimal('1658.1429'))
('노원구', 'SK에너지', Decimal('1662.0000'))
('관악구', 'SK에너지', Decimal('1665.5000'))
('금천구', '현대오일뱅크', Decimal('1666.5000'))
('송파구', 'GS칼텍스', Decimal('1667.2500'))
('노원구', 'GS칼텍스', Decimal('1670.7500'))
('강서구', 'GS칼텍스', Decimal('1674.5000'))
('금천구', 'GS칼텍스', Decimal('1675.0000'))
('성북구', 'S-OIL', Decimal('1675.5000'))
('서대문구', 'SK에너지', Decimal('1677.0000'))
('광진구', 'S-OIL', Decimal('1682.0000'))
('동작구', 'GS칼텍스', Decimal('1684.0000'))
('동작구', '현대오일뱅크', Decimal('1685.2000'))
('서초구', 'GS칼텍스', Decimal('1687.2857'))
('서초구', '현대오일뱅크', Decimal('1689.2000'))
('송파구', '현대오일뱅크', Decimal('1692.0000'))
('송파구', 'SK에너지', Decimal('1693.8889'))
('강서구', 'S-OIL', Decimal('1696.6000'))
('은평구', '자가상표', Decimal('1698.0000'))
('동작구', 'S-OIL', Decimal('1699.0000'))
('강동구', 'SK에너지', Decimal('1699.3333'))
('구로구', 'S-OIL', Decimal('1702.3333'))
('마포구', 'SK에너지', Decimal('1703.7500'))
('강서구', 'SK에너지', Decimal('1708.0000'))
('관악구', 'S-OIL', Decimal('1711.5000'))
('강동구', 'GS칼텍스', Decimal('1728.8000'))
('광진구', 'SK에너지', Decimal('1737.6667'))
('서초구', 'S-OIL', Decimal('1740.5000'))
('영등포구', 'GS칼텍스', Decimal('1745.5000'))
('강동구', '현대오일뱅크', Decimal('1746.0000'))
('관악구', 'GS칼텍스', Decimal('1746.5000'))
('성동구', '현대오일뱅크', Decimal('1752.3333'))
('서초구', 'SK에너지', Decimal('1754.1429'))
('종로구', '현대오일뱅크', Decimal('1759.0000'))
('영등포구', 'SK에너지', Decimal('1761.5000'))
('중구', '알뜰주유소', Decimal('1768.0000'))
('종로구', 'S-OIL', Decimal('1779.5000'))
('중구', 'S-OIL', Decimal('1785.0000'))
('성동구', 'SK에너지', Decimal('1788.5000'))
('강남구', 'SK에너지', Decimal('1840.0909'))
('강동구', 'S-OIL', Decimal('1859.0000'))
('강남구', 'S-OIL', Decimal('1875.0000'))
('강남구', '현대오일뱅크', Decimal('1959.6250'))
('종로구', 'SK에너지', Decimal('1983.5000'))
('강남구', 'GS칼텍스', Decimal('2020.3333'))
('용산구', '현대오일뱅크', Decimal('2056.5000'))
('중구', 'SK에너지', Decimal('2143.5000'))
('용산구', 'SK에너지', Decimal('2211.2000'))
('용산구', 'GS칼텍스', Decimal('2366.0000'))
('중구', 'GS칼텍스', Decimal('2489.0000'))

---